New  documentation and tutorials
openkinome/kinoml pull request #128
Opened 2023-11-17 16:55 UTC by raquellrios

## Description
KinoML new tutorials, docs and figures.

## Todos
Final docs and tutorials for KinoML tech paper

## Status
- [ ] Ready to go

2023-12-08 19:05 UTC, ijpulidos requested changes
This is looking great! Amazing work. I just added a few comments on some changes I think we should make to the install instructions.

Also, do we need to have a copy of the `kinoml/data` subdir in the docs directory? Seems like we should avoid having copies of the data here, as possible.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/README.md
Do we need to add all the files in the `kinoml/data` subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/electron_densities/4f8o_phases.mtz
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/electron_densities/__init__.py
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/kinomescan/DiscoverX_489_Kinase_Assay_Construct_Information.csv
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/kinomescan/journal.pone.0181585.s004.csv
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/look_and_say.dat
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/molecules/__init__.py
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/molecules/chloroform.pdb
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/molecules/chloroform.sdf
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/molecules/chloroform_acetamide.pdb
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/molecules/chloroform_acetamide.sdf
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/object_model.png
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/proteins/README.md
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on docs/kinoml/data/proteins/__init__.py
Do we need to add all the files in the kinoml/data subdir here as well? We should avoid having two copies of the same files and data here.

2023-12-08 19:05 UTC, ijpulidos commented on kinoml/data/fig_1_kinomltechpaper_v2.png
I love the summary in this figure, great work!

2023-12-20 14:45 UTC, AndreaVolkamer approved these changes
Looks great. thanks!

2023-12-20 14:46 UTC, AndreaVolkamer commented
I think the changes requested by @ijpulidos were addressed by @raquellrios, so I will go ahead and merge the PR.

2023-12-20 14:48 UTC, merged